server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to the gateway if needed from frontend
    # However, since we use absolute URL in axios, this is optional
    # but good for production with relative paths.
    location /api {
        proxy_pass http://gateway-service:8060;
    }
}
